apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.0"
spec:
  rules:
    - host: swsp.com
      http:
        paths:
          #Eventbus
          - path: /eventbus
            pathType: Prefix
            backend:
              service:
                name: event-bus-clusterip-srv
                port:
                  number: 80
          #Nats
          - path: /nats
            pathType: Prefix
            backend:
              service:
                name: nats-clusterip-srv
                port:
                  number: 4222
          #Technical Health Dashboard
          - path: /
            pathType: Prefix
            backend:
              service:
                name: technical-health-dashboard-clusterip-srv
                port:
                  number: 80
          #Technical Health Service
          - path: /servicestates
            pathType: Prefix
            backend:
              service:
                name: technical-health-service-clusterip-srv
                port:
                  number: 80
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: technical-health-service-clusterip-srv
                port:
                  number: 80
          #Raw Data Service
          - path: /publishheart
            pathType: Prefix
            backend:
              service:
                name: raw-data-service-clusterip-srv
                port:
                  number: 80
          - path: /publishskin
            pathType: Prefix
            backend:
              service:
                name: raw-data-service-clusterip-srv
                port:
                  number: 80
          - path: /measurements
            pathType: Prefix
            backend:
              service:
                name: raw-data-service-clusterip-srv
                port:
                  number: 80
          #Sensor Data Service
          - path: /measurements/RR
            pathType: Prefix
            backend:
              service:
                name: sensor-data-service-clusterip-srv
                port:
                  number: 80
          - path: /measurements/SkinConductance
            pathType: Prefix
            backend:
              service:
                name: sensor-data-service-clusterip-srv
                port:
                  number: 80


          

